# Generated by Django 5.2.1 on 2025-05-22 11:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AppSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_image', models.ImageField(blank=True, null=True, upload_to='app_images/')),
                ('app_name', models.CharField(max_length=255)),
                ('app_link', models.URLField()),
                ('app_category', models.CharField(choices=[('Productivity', 'Productivity'), ('Entertainment', 'Entertainment'), ('Education', 'Education'), ('Social', 'Social')], max_length=50)),
                ('subcategory', models.CharField(choices=[('Task Management', 'Task Management'), ('Note Taking', 'Note Taking'), ('Time Tracking', 'Time Tracking'), ('Project Management', 'Project Management'), ('Collaboration Tools', 'Collaboration Tools'), ('Calendar Apps', 'Calendar Apps'), ('Document Editing', 'Document Editing'), ('Workflow Automation', 'Workflow Automation'), ('Streaming', 'Streaming'), ('Gaming', 'Gaming'), ('Music', 'Music'), ('Video Editing', 'Video Editing'), ('Live Events', 'Live Events'), ('Podcasts', 'Podcasts'), ('Virtual Reality', 'Virtual Reality'), ('Photo Editing', 'Photo Editing'), ('Learning Platforms', 'Learning Platforms'), ('Language Learning', 'Language Learning'), ('Tutoring', 'Tutoring'), ('Online Courses', 'Online Courses'), ('Study Tools', 'Study Tools'), ('Educational Games', 'Educational Games'), ('Research Tools', 'Research Tools'), ('Skill Development', 'Skill Development'), ('Messaging', 'Messaging'), ('Networking', 'Networking'), ('Community', 'Community'), ('Social Media', 'Social Media'), ('Event Planning', 'Event Planning'), ('Dating Apps', 'Dating Apps'), ('Forums', 'Forums'), ('Content Sharing', 'Content Sharing')], max_length=50)),
                ('points', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ScreenshotSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_screenshot', models.ImageField(blank=True, null=True, upload_to='screenshots/')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('app_submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.appsubmission')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
